import type { Template } from "@/shared/types/entities";

import type { CreateInput } from "../types";

export const createBuiltInTemplates = (): CreateInput<Template>[] => [
  {
    title: "Коннект инженеру — просьба о реферале (EN)",
    lang: "en",
    audience: "engineer",
    scenario: "connect_note",
    body: "Hi {{contactName}}, I applied for {{vacancyTitle}} at {{company}} today. Frontend engineer, 5 years of React and TypeScript. Would you be open to referring me?",
    isBuiltIn: true,
  },
  {
    title: "Коннект инженеру — просьба о реферале (RU)",
    lang: "ru",
    audience: "engineer",
    scenario: "connect_note",
    body: "Здравствуйте, {{contactName}}. Сегодня откликнулся на {{vacancyTitle}} в {{company}}. Фронтенд, 5 лет на React и TypeScript. Готовы дать реферал?",
    isBuiltIn: true,
  },
  {
    title: "Коннект нанимающему — есть вакансия (EN)",
    lang: "en",
    audience: "hiring",
    scenario: "connect_note",
    body: "Hi {{contactName}}, I applied for {{vacancyTitle}} at {{company}} today. Frontend engineer, 5 years of React and TypeScript, relocating to the region. Open to 15 minutes this week?",
    isBuiltIn: true,
  },
  {
    title: "Коннект нанимающему — есть вакансия (RU)",
    lang: "ru",
    audience: "hiring",
    scenario: "connect_note",
    body: "Здравствуйте, {{contactName}}. Сегодня откликнулся на {{vacancyTitle}} в {{company}}. Фронтенд, 5 лет на React и TypeScript, переезжаю в регион. Найдётся 15 минут на этой неделе?",
    isBuiltIn: true,
  },
  {
    title: "Коннект нанимающему — вакансий нет (EN)",
    lang: "en",
    audience: "hiring",
    scenario: "no_vacancy",
    body: "Hi {{contactName}}, frontend engineer with 5 years of React and TypeScript, relocating to the region. No open frontend role at {{company}} right now — would you keep me in the pipeline for the next one?",
    isBuiltIn: true,
  },
  {
    title: "Коннект нанимающему — вакансий нет (RU)",
    lang: "ru",
    audience: "hiring",
    scenario: "no_vacancy",
    body: "Здравствуйте, {{contactName}}. Фронтенд-инженер, 5 лет на React и TypeScript, переезжаю в регион. Открытых фронтенд-вакансий в {{company}} сейчас нет — можно попасть в пайплайн до публикации?",
    isBuiltIn: true,
  },
  {
    title: "Полное сообщение после коннекта — инженеру (EN)",
    lang: "en",
    audience: "engineer",
    scenario: "referral_request",
    body: "Thanks for connecting, {{contactName}}.\n\nI am a frontend engineer with 5 years of React and TypeScript, currently applying to {{company}} for {{vacancyTitle}}: {{vacancyUrl}}\n\nWhat drew me in: {{productDetail}}\n\nA referral from your side would put the application in a different queue. If that works for you, I can send anything you need — CV, a short summary, or the exact role link. My work is here: {{portfolioUrl}}\n\nThank you for your time and assistance.\n{{myName}}",
    isBuiltIn: true,
  },
  {
    title: "Полное сообщение после коннекта — нанимающему (EN)",
    lang: "en",
    audience: "hiring",
    scenario: "full_message",
    body: "Thanks for connecting, {{contactName}}.\n\nI applied for {{vacancyTitle}} at {{company}} and wanted to give you the short version: 5 years as a frontend engineer, React and TypeScript, product teams with real traffic, and recent production work with LLM-based features.\n\nWhat drew me to {{company}}: {{productDetail}}\n\nI am relocating to the region and am ready for an employment visa process. Would 15 minutes this week work for you?\n\nThank you for your time and assistance.\n{{myName}}",
    isBuiltIn: true,
  },
  {
    title: "Follow-up 1 — день 5 (EN)",
    lang: "en",
    audience: "any",
    scenario: "follow_up_1",
    body: "Hi {{contactName}}, following up on my note about {{vacancyTitle}} at {{company}}. Still interested and happy to answer anything about my background.",
    isBuiltIn: true,
  },
  {
    title: "Follow-up 1 — день 5 (RU)",
    lang: "ru",
    audience: "any",
    scenario: "follow_up_1",
    body: "Здравствуйте, {{contactName}}. Возвращаюсь к сообщению про {{vacancyTitle}} в {{company}}. Интерес в силе, готов ответить на любые вопросы по опыту.",
    isBuiltIn: true,
  },
  {
    title: "Follow-up 2 — последний (EN)",
    lang: "en",
    audience: "any",
    scenario: "follow_up_2",
    body: "Hi {{contactName}}, last note from me on {{vacancyTitle}} at {{company}}. If the timing is wrong, no problem — my details are here: {{portfolioUrl}}. Happy to talk whenever a frontend role opens up.",
    isBuiltIn: true,
  },
  {
    title: "Proof-of-work — разбор их фронтенда (EN)",
    lang: "en",
    audience: "any",
    scenario: "proof_of_work",
    body: "Hi {{contactName}}, I spent an evening with {{company}}'s web app out of curiosity and wrote down three frontend findings with numbers — load time, bundle size on the first route, and a rendering detail: {{portfolioUrl}}\n\nNo agenda, just the kind of thing I enjoy digging into. Happy to walk through it if it is useful.",
    isBuiltIn: true,
  },
  {
    title: "Письмо после этапа (EN)",
    lang: "en",
    audience: "any",
    scenario: "thank_you",
    body: "Thank you for the conversation today. {{productDetail}} was the part that stayed with me, and it lines up with the work I want to be doing next.\n\nMy interest in {{vacancyTitle}} at {{company}} stands, and I am ready for the next step whenever you are.\n\nThank you for your time and assistance.\n{{myName}}",
    isBuiltIn: true,
  },
];
